"""Fubon Neo securities TEST-environment read-only adapter."""

from tw_stock_tool.broker_adapters.fubon_neo.account_readiness import (
    FUBON_NEO_ACCOUNT_EVIDENCE_SHA256,
    FUBON_NEO_ACCOUNT_EVIDENCE_VERSION,
    FUBON_NEO_ACCOUNT_FACT_CONTRACT_VERSION,
    FUBON_NEO_ACCOUNT_FACT_EVIDENCE,
    FubonNeo56_5DReadiness,
    FubonNeoAccountFactReadiness,
    current_fubon_neo_56_5d_readiness,
    current_fubon_neo_account_fact_readiness,
)
from tw_stock_tool.broker_adapters.fubon_neo.adapter import (
    FubonNeoIncompleteAccountRead,
    FubonNeoReadonlyAdapter,
    FubonNeoReadonlyPort,
    require_fubon_neo_sdk,
)
from tw_stock_tool.broker_adapters.fubon_neo.config import (
    FUBON_NEO_BROKER_ID,
    FUBON_NEO_CATALOG_EVIDENCE_SHA256,
    FUBON_NEO_CATALOG_MEMBERSHIP_SHA256,
    FUBON_NEO_CATALOG_SCHEMA_VERSION,
    FUBON_NEO_CATALOG_SOURCE_VERSION,
    FUBON_NEO_CURRENCY,
    FUBON_NEO_MARKET,
    FUBON_NEO_SDK_VERSION,
    FUBON_NEO_SOURCE_VERSION,
    FUBON_NEO_TEST_CONNECTION_IDENTITY,
    FUBON_NEO_TEST_ENDPOINT,
    FUBON_NEO_TPEX_CATALOG_ENDPOINT,
    FUBON_NEO_TWSE_CATALOG_ENDPOINT,
    FubonNeoInstrumentCatalog,
    FubonNeoInstrumentMarket,
    FubonNeoReadConnectionIdentity,
    FubonNeoTestConfig,
    build_reviewed_instrument_catalog,
)
from tw_stock_tool.broker_adapters.fubon_neo.errors import (
    FubonNeoErrorCode,
    FubonNeoReadError,
)
from tw_stock_tool.broker_adapters.fubon_neo.mapper import (
    FubonNeoCashObservation,
    exact_decimal,
    map_capabilities,
    map_cash,
    map_open_orders,
    map_positions,
    unwrap_provider_result,
)


__all__ = [
    "FUBON_NEO_ACCOUNT_EVIDENCE_SHA256",
    "FUBON_NEO_ACCOUNT_EVIDENCE_VERSION",
    "FUBON_NEO_ACCOUNT_FACT_CONTRACT_VERSION",
    "FUBON_NEO_ACCOUNT_FACT_EVIDENCE",
    "FUBON_NEO_BROKER_ID",
    "FUBON_NEO_CATALOG_EVIDENCE_SHA256",
    "FUBON_NEO_CATALOG_MEMBERSHIP_SHA256",
    "FUBON_NEO_CATALOG_SCHEMA_VERSION",
    "FUBON_NEO_CATALOG_SOURCE_VERSION",
    "FUBON_NEO_CURRENCY",
    "FUBON_NEO_MARKET",
    "FUBON_NEO_SDK_VERSION",
    "FUBON_NEO_SOURCE_VERSION",
    "FUBON_NEO_TEST_CONNECTION_IDENTITY",
    "FUBON_NEO_TEST_ENDPOINT",
    "FUBON_NEO_TPEX_CATALOG_ENDPOINT",
    "FUBON_NEO_TWSE_CATALOG_ENDPOINT",
    "FubonNeoCashObservation",
    "FubonNeo56_5DReadiness",
    "FubonNeoAccountFactReadiness",
    "FubonNeoErrorCode",
    "FubonNeoIncompleteAccountRead",
    "FubonNeoInstrumentCatalog",
    "FubonNeoInstrumentMarket",
    "FubonNeoReadConnectionIdentity",
    "FubonNeoReadError",
    "FubonNeoReadonlyAdapter",
    "FubonNeoReadonlyPort",
    "FubonNeoTestConfig",
    "build_reviewed_instrument_catalog",
    "current_fubon_neo_56_5d_readiness",
    "current_fubon_neo_account_fact_readiness",
    "exact_decimal",
    "map_capabilities",
    "map_cash",
    "map_open_orders",
    "map_positions",
    "require_fubon_neo_sdk",
    "unwrap_provider_result",
]
